services:
  postgres:
    image: postgres:17.2-alpine
    restart: always
    networks:
      - db
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=maptiler_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 2s
      retries: 10
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    networks:
      - db
    ports:
      - 8080:8080
    environment:
      - ADMINER_DEFAULT_SERVER=postgres

networks:
  db:

volumes:
  postgres_data:
